### ISSUE TITLE
Cannot install on Debian Stretch

### ISSUE THREAD

**Issue by rkkoszewski** [claudyus/LXC-Web-Panel#121]
It seems that it's not possible to install this on Debian Stretch. I followed the instructions from here: https://packagecloud.io/claudyus/LXC-Web-Panel/install

Running: apt-get install lwp
yields as result: E: Unable to locate package lwp

Any suggestions?

**Comment by n3storm** [comment]
Even if you install from here https://packagecloud.io/claudyus/LXC-Web-Panel version 0.9 is two years old.

What I have done in Debian 9 Stretch is:
``` 
apt-get install python-ldap
git clone https://github.com/claudyus/LXC-Web-Panel.git
cd LXC-Web-Panel/jsbuild
npm install
node_modules/.bin/bower install --allow-root
node_modules/.bin/grunt --allow-root
cd ..
python setup.py install
mkdir /etc/lwp
cp lwp.example.conf /etc/lwp/lwp.conf
mkdir /var/lwp
cp lwp.db /var/lwp/lwp.db
```

You can run lwp now. Default credentials are admin/admin. Don't forget to change password  at domain:5000/lwp/users
