### ISSUE TITLE
"service lwp start" doesn't work.

### ISSUE THREAD

**Issue by jots** [claudyus/LXC-Web-Panel#52]
Following the instructions in README.rst:
wget -O - http://claudyus.github.io/LXC-Web-Panel/claudyus.gpg.key | sudo apt-key add -
echo "deb http://claudyus.github.io/LXC-Web-Panel/ debian/" | sudo tee /etc/apt/sources.list.d/lwp.list
sudo apt-get update
sudo apt-get install lwp

$ service lwp start
start: Unknown job: lwp

no lwp in /etc/init.d
I am on ubuntu 14.04.

/usr/sbin/lwp works, just not added to startup.
how to add to startup?

**Comment by claudyus** [comment]
I believe that you try it without root privilege.

You should run this with sudo or as root:
```
$ service lwp start
start: Unknown job: lwp
$ sudo service lwp start
lwp start/running, process 9397
```
