### ISSUE TITLE
RPM based distro support

### ISSUE THREAD

**Issue by kallisti5** [claudyus/LXC-Web-Panel#53]
Fedora 21 is out, and their server offering is pretty competitive with Ubuntu (Up to date RPM packages + modernization)

I'm going to spin up a Fedora 21 VM to see if I can get this running there with minimal effort :-)

**Comment by claudyus** [comment]
I would be very happy to merge such improvement!

**Comment by kallisti5** [comment]
steps so far:

```
sudo yum update
sudo yum install lxc lxc-devel lxc-libs lxc-extra python-pam python-flask

./setup.py install

mkdir -p /etc/lwp
mkdir -p /var/lwp

cp lwp.example.conf /etc/lwp/lwp.conf
cp lwp.db /var/lwp/lwp.db

service firewalld stop
service lxc start

lwp
```

**Comment by kallisti5** [comment]
Is there a default username/password for database auth? I don't see it documented.

**Comment by claudyus** [comment]
admin/admin

I was pretty sure that this was in readme file. I will readd it soon!

**Comment by kallisti5** [comment]
Finally have some base functionality on Fedora 21. Here are the latest steps:
```
sudo yum update
sudo yum install lxc lxc-devel lxc-libs lxc-extra lxc-templates python-pam python-flask fabric pytz npm

fab build_assets
./setup.py develop

mkdir -p /etc/lwp
mkdir -p /var/lwp

cp lwp.example.conf /etc/lwp/lwp.conf
cp lwp.db /var/lwp/lwp.db

service firewalld stop
service lxc start

./bin/lwp --debug
```

**Comment by claudyus** [comment]
@kallisti5 can you expand the Readme with those installation info for rpm based systems?

**Comment by kallisti5** [comment]
I was actually going to... But then figured out the readme was some crazy obscure python markdown format and opened a ticket instead. ;-)
