### ISSUE TITLE
Missing bootstrap css

### ISSUE THREAD

**Issue by kallisti5** [claudyus/LXC-Web-Panel#56]
http://192.168.1.118:5000/static/css/bootstrap.min.css is missing,

it looks like it isn't in the git repo but is linked to from the main page:

 <link href="/static/css/bootstrap.min.css" rel="stylesheet">

**Comment by claudyus** [comment]
If you want to install lwp from git you should execute ``fab build_assets`` to download and build minified js. You also need a recent version of nodejs installed
