### ISSUE TITLE
internal server error upon first login if LXC not yet installed

### ISSUE THREAD

**Issue by dethegeek** [claudyus/LXC-Web-Panel#60]
Hi

I'm running Ubuntu 14.04 LTS. 

I installed LWP, tried to login and I got an internal server error. After some searches and found several issues related to the content of /var/lib/lxc I found LWP crashes if LXC is not yet installed. 

LWP should check if /var/lib/lxc exists and show a more friendly message.

After a apt-get install lxc, lwp works (at least I can login)

**Comment by cocoy** [comment]
Just curious how did you install lwp?
If using apt-get,  lwp requires lxc. So I assume lxc should be installed, unless there is something wrong with the packaging. :)

**Comment by dethegeek** [comment]
Hi

I used the command line provided in the web page "get started" from the project's website because it's very efficient, 

I simply did not checked if LWP is available in Ubuntu's packages.

By the way, will LWP work on Debian (jessie) in a near future ?

**Comment by dethegeek** [comment]
OK, After following your own setup instructions, it works fine, and the package dependancy will do the trick. 

sorry for the inconvenience
