### ISSUE TITLE
Cannot make CT setting changes with certain hostnames

### ISSUE THREAD

**Issue by luckyjay** [claudyus/LXC-Web-Panel#69]
Hi,

If I create a new CT named "test_ct", I can no longer change any settings, or even re-apply current settings. After pressing "Apply" at the bottom, the page scrolls to the top, highlights the hostname box in Red and says  "Please match the requested format".

**Comment by claudyus** [comment]
I just commit a fix on the regex but the hostname is not updated on container. So the another bug require more investigation (or just disable the input text)...

**Comment by claudyus** [comment]
I didn't see the #68 that is related to hostname change so this issues can be closed

**Comment by claudyus** [comment]
I fix this issues. Now the new hostname is saved in config file but, anyway, the hostname is not updated inside the container after restart. I think this form field is really useless...
