### ISSUE TITLE
Interface will not allow save when overlayfs clone created

### ISSUE THREAD

**Issue by chorca** [claudyus/LXC-Web-Panel#72]
After using the interface to clone a container (the switch is unlabeled), the Root FS is now listed as "overlayfs:/storage/lxc/templatecontainer/rootfs:/storage/lxc/newcontainer/delta0". The container can be launched and works properly, but attempting to change the container settings using the interface will not succeed, as the interface does not allow the Root FS field to contain the new "overlayfs:" storage.

**Comment by claudyus** [comment]
Should be fixed with this regex rewrite. If not please reopen the ticket
