### ISSUE TITLE
lxc.mount.entry entries thrown away on config change

### ISSUE THREAD

**Issue by the-mars** [claudyus/LXC-Web-Panel#73]
If I change something in an LXC container from LWP I am left alone with one `lxc.mount.entry`. And restarting my LXC will result in a system that sticks in its boot sequence.

Before editing the config it looks like:
```
lxc.mount = /var/lib/lxc/mycontainer/fstab
lxc.mount.entry = proc proc proc nodev,noexec,nosuid 0 0
lxc.mount.entry = sysfs sys sysfs defaults 0 0
lxc.mount.entry = /sys/fs/fuse/connections sys/fs/fuse/connections none bind,optional 0 0
lxc.mount.entry = /sys/kernel/debug sys/kernel/debug none bind,optional 0 0
lxc.mount.entry = /sys/kernel/security sys/kernel/security none bind,optional 0 0
lxc.mount.entry = /sys/fs/pstore sys/fs/pstore none bind,optional 0 0
lxc.tty = 4
lxc.pts = 1024
lxc.devttydir = lxc
...
```

After editing:
```
lxc.mount = /var/lib/lxc/mycontainer/fstab
lxc.mount.entry = /sys/fs/pstore sys/fs/pstore none bind,optional 0 0
lxc.tty = 4
lxc.pts = 1024
lxc.devttydir = lxc
...
```

The container can be made bootable by readding the missing lines.

I think your great LWP cannot handle multiple `lxc.mount.entry` lines. Maybe you can fix it in the same way as for the `lxc.cgroup.devices.allow` lines?

**Comment by claudyus** [comment]
So this [1] patch doesn't works or you are testing a previous version of lwp? 

1. https://github.com/claudyus/LXC-Web-Panel/commit/8133fae1e170a666aaf4ce893fa3112ce791438d

**Comment by the-mars** [comment]
Thanks for your reply.
Sorry, I was not running the latest version. Because auto updating in Ubuntu did reset the admin password continuously. But that is another issue.
