### ISSUE TITLE
Not installing on Debian Jessie RC1

### ISSUE THREAD

**Issue by svennieslony** [claudyus/LXC-Web-Panel#78]
I'm not certain this is meant to work under Debian, but when following the guide "Installation on deb based system" I run into an error:

Setting up lwp (0.8-25-g62597b1) ...
 * missed /etc/lwp/lwp.conf file
 * cannot read config files. Exit!
dpkg: error processing package lwp (--configure):
 subprocess installed post-installation script returned error exit status 102
Processing triggers for libc-bin (2.19-17) ...
Errors were encountered while processing:
 lwp
E: Sub-process /usr/bin/dpkg returned an error code (1)

I manually copied the example file by "cp /etc/lwp/lwp.example.conf /etc/lwp/lwp.conf" and tried again but it still fails:

Setting up lwp (0.8-25-g62597b1) ...
 * Auth type: database
dpkg: error processing package lwp (--configure):
 subprocess installed post-installation script returned error exit status 102
Errors were encountered while processing:
 lwp
E: Sub-process /usr/bin/dpkg returned an error code (1)

Is there anything I can do?

Thanks!
Sven

**Comment by claudyus** [comment]
Hi @svennieslony 
I use those project on some ubuntu server but I don't see any problem to run in on debian or centos distro, so also if I suggest to use ubuntu I pretty happy to fix stuff to be more distro independent as possible.

On your error now, during the installatio progess the debian hook will call this script https://github.com/claudyus/LXC-Web-Panel/blob/master/debian/lwp.postinst to generate the secret session token if it doesn't exists.

Can you try to directly run ```/usr/bin/lwp --generate-session-secret``` as root to see if the same error is reported?
It should not involve the config file or db during this operation. This is really strange behaviors.

**Comment by svennieslony** [comment]
Hi Claudyus,

This runs fine:
/usr/bin/lwp --generate-session-secret
 * Auth type: database

I can also start lwp by running /usr/bin/lwp 
 * Auth type: database
 * Running on http://0.0.0.0:5000/

lwp is is accessible as expected. It seems like something in the posttest script is not working. I will try to do some debuging...

Thanks for the quick reply!

**Comment by svennieslony** [comment]
delete me
