### ISSUE TITLE
Install error on Debian Jessie

### ISSUE THREAD

**Issue by miguelzabala** [claudyus/LXC-Web-Panel#79]
Debian 8
Fresh install

Setting up lwp (0.8-25-g62597b1) ...
dpkg: error processing package lwp (--configure):
 subprocess installed post-installation script returned error exit status 102
Errors were encountered while processing:
 lwp
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by miguelzabala** [comment]
The problem is with the postinstall script
/var/lib/dpkg/info/lwp.postinst

I think it's because the change to systemd

**Comment by claudyus** [comment]
Hi @miguelzabala 

I believe that this is the same bug of #78 I commit a workaround in https://github.com/claudyus/LXC-Web-Panel/commit/3cffd347c17ce70ab1c55b3091bc8d7bbc10ac93 but is not yet in debian package

Are you sure that the problem is in systemd?

**Comment by miguelzabala** [comment]
Hello @claudyus , 

I'm pretty sure it's the problem is with systemd.

**Comment by cronner** [comment]
any fix yet?

Setting up lwp (0.8-25-g62597b1) ...
 * missed /etc/lwp/lwp.conf file
 * cannot read config files. Exit!
dpkg: error processing package lwp (--configure):
 subprocess installed post-installation script returned error exit status 102
Errors were encountered while processing:
 lwp
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by yoav-steinberg** [comment]
Just create PR https://github.com/claudyus/LXC-Web-Panel/pull/82 trying to resolve this.

**Comment by claudyus** [comment]
fixed with merge
