### ISSUE TITLE
Review the debian package release process

### ISSUE THREAD

**Issue by cronner** [claudyus/LXC-Web-Panel#84]
# sudo apt-get install lwp
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following extra packages will be installed:
  python-ldap
Suggested packages:
  python-ldap-doc python-pyasn1
The following NEW packages will be installed:
  lwp python-ldap
0 upgraded, 2 newly installed, 0 to remove and 0 not upgraded.
Need to get 332 kB of archives.
After this operation, 2,391 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
WARNING: The following packages cannot be authenticated!
  lwp
Install these packages without verification? [y/N] y
Get:1 http://mirrors.online.net/debian/ jessie/main python-ldap amd64 2.4.10-1 [120 kB]
Get:2 http://claudyus.github.io/LXC-Web-Panel/ debian/ lwp 0.8-65-gcbc803f [212 kB]
Fetched 332 kB in 0s (741 kB/s)
E: Failed to fetch http://claudyus.github.io/LXC-Web-Panel/debian//lwp_0.8-65-gcbc803f_all.deb  Size mismatch

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

**Comment by claudyus** [comment]
``fab site`` need some review.. package removed see:

https://github.com/claudyus/LXC-Web-Panel/tree/needfix_84

**Comment by cronner** [comment]
Was on Debian Jessie

**Comment by claudyus** [comment]
I'm next to adopt https://packagecloud.io to release debian packages

https://packagecloud.io/claudyus/LXC-Web-Panel

**Comment by claudyus** [comment]
with the new 0.9 release I'm using packagecloud.io. This should grant a more realiable package release
