### ISSUE TITLE
CT name causes problem with rootfs parse

### ISSUE THREAD

**Issue by alitvak69** [claudyus/LXC-Web-Panel#86]
If I create a CT with  host name foo-light, I can no longer make changes to the container.  While more permissive regex is allowing hostname, it doesn't allow the same format for rootfs.  So bug #69 is not fully fixed, please fix it.

**Comment by claudyus** [comment]
I yet pushed a fix for it, otherwise the package release process need review and I'm not going to release a new deb package immediately.

**Comment by alitvak69** [comment]
Can I build a deb package based on your master then?

**Comment by claudyus** [comment]
Can you try a package from https://packagecloud.io/claudyus/LXC-Web-Panel

I'm trying a new debian package release process.

**Comment by alitvak69** [comment]
I tried this using bash script.  It looks interesting.  One problem, new package overwrote security database lwp.db changing it to a default admin / admin.  

Other then that dash in hostname works now.  Default gateway on the other hand showed as unexpected format (highlighted yellow) but it let me  apply anyway.  

Thank you for a quick fix.

**Comment by claudyus** [comment]
Yes the database override on reinstall is a well know problem and is not easly fixable. I could suggest another login provider to workaround the problem or contribute in sqlalchemy migration (sql branch).

**Comment by yswery** [comment]
Can confirm on my end when you create a CT with a hyphen it you can not longer edit it later:

![error image](http://i.imgur.com/VZy5weQ.png "Validation Error")

**Comment by claudyus** [comment]
fixes released in 0.9
