### ISSUE TITLE
small issues, I've found.

### ISSUE THREAD

**Issue by ddark-il** [claudyus/LXC-Web-Panel#89]
System: Ubuntu 14.04, no additional repositories, fully updated

1. Reboot button not working
2. Local disk backup reports "failed" even if it finished correctly
3. Cloning work only with turned-off machine, not sure if a bug, but the button shouldn't appear if it's not a bug.
4. Project's website lacking of "buy me a beer button"

Thanks for your work, planing to use it on small-scale production servers. Would be nice if you could also integrate it with nginx, some firewall and ssh from panel, like it been done in ajenti panel(maybe you can use their code).

**Comment by claudyus** [comment]
Hi @ddark-il
I should definitely add a buy me beer botton ;) 

I'm going to push some patches for those issues.
Thanks for your feedback

**Comment by linbynd** [comment]
Just started Using it an hour ago. Using it on Ubuntu 15.04 and it works like a charm. Though I still have to create a systemd Unit file for it. I am not sure if has the ability to use new bridges as I have a br0 that my containers are running on. Also a destroy button would be handy i think.

**Comment by claudyus** [comment]
Most ofl issues here reported should be now fixed in 0.9.
