### ISSUE TITLE
unsupported backing store option

### ISSUE THREAD

**Issue by djbobyd** [claudyus/LXC-Web-Panel#92]
Hi,
Thanks for the great project. I really like it. If you could just add support for the loop backing store as it is quite convenient to create the filesystem in a container file instead of having the raw directory structure. Unfortunately the loop backing store is not supported and I get "Not in the expected format" which prevents me from saving any other changes to the container. the format for the loop backing store looks like this: loop:/var/lib/lxc/\<name\>/rootdev

Thanks a lot

**Comment by claudyus** [comment]
Hi @djbobyd 
can you try to change the regex here https://github.com/claudyus/LXC-Web-Panel/blob/master/lwp/utils.py#L33 and report your results or open a PR?

Here a regex that match also with ```loop``` prefix ```^(\/|loop:|overlayfs:\/)[\w.\/:-]+$"```

**Comment by djbobyd** [comment]
Works like a charm :+1: 
Thanks lot for the fast reply
