### ISSUE TITLE
no files being installed

### ISSUE THREAD

**Issue by lgwapnitsky** [claudyus/LXC-Web-Panel#93]
The config file refs /srv/lwp for the python file.  This is not populated using the debian install on Ubuntu 14.04

a search for the filename lwp.py on the system reveals nothing

**Comment by lgwapnitsky** [comment]
update....files are installed, but service does not work.  created a dir called /srv/lwp, but service only starts if I manually run the lwp executable.

**Comment by claudyus** [comment]
I believe that you are missing the configuration file part here.
Anyway no ref to /srv/lwp are in the code now. Where did you found those refs?

**Comment by claudyus** [comment]
reopen the issues if needed
