### ISSUE TITLE
Rootfs

### ISSUE THREAD

**Issue by rebootit** [claudyus/LXC-Web-Panel#95]
if the root fs name contain '-' the check fails and I can't save my container.
With the regex that checks the validity of this field (in utils.py) modified like this ^\/\w[\w\--/]+$ it's ok.

... ooops, sorry, I haven't checked he previous issues, and i has already been reported...

**Comment by lcherone** [comment]
same issue here...bump

**Comment by claudyus** [comment]
should be fixed with release 0.9 by packagecloud.io, see Readme
